INSERT INTO kabupaten_kota ("provinsi_id","name") VALUES
( 11,'Aceh Selatan'),
( 11,'Aceh Tenggara'),
( 11,'Aceh Timur'),
( 11,'Aceh Tengah'),
( 11,'Aceh Barat'),
( 11,'Aceh Besar'),
( 11,'Pidie'),
( 11,'Aceh Utara'),
( 11,'Simeulue'),
( 11,'Aceh Singkil'),
( 11,'Bireuen'),
( 11,'Aceh Barat Daya'),
( 11,'Gayo Lues'),
( 11,'Aceh Jaya'),
( 11,'Nagan Raya'),
( 11,'Aceh Tamiang'),
( 11,'Bener Meriah'),
( 11,'Pidie Jaya'),
( 11,'Kota Banda Aceh'),
( 11,'Kota Sabang'),
( 11,'Kota Lhokseumawe'),
( 11,'Kota Langsa'),
( 11,'Kota Subulussalam'),
( 12,'Tapanuli Tengah'),
( 12,'Tapanuli Utara'),
( 12,'Tapanuli Selatan'),
( 12,'Nias'),
( 12,'Langkat'),
( 12,'Karo'),
( 12,'Deli Serdang'),
( 12,'Simalungun'),
( 12,'Asahan'),
( 12,'Labuhanbatu'),
( 12,'Dairi'),
( 12,'Toba'),
( 12,'Mandailing Natal'),
( 12,'Nias Selatan'),
( 12,'Pakpak Bharat'),
( 12,'Humbang Hasundutan'),
( 12,'Samosir'),
( 12,'Serdang Bedagai'),
( 12,'Batu Bara'),
( 12,'Padang Lawas Utara'),
( 12,'Padang Lawas'),
( 12,'Labuhanbatu Selatan'),
( 12,'Labuhanbatu Utara'),
( 12,'Nias Utara'),
( 12,'Nias Barat'),
( 12,'Kota Medan'),
( 12,'Kota Pematangsiantar'),
( 12,'Kota Sibolga'),
( 12,'Kota Tanjung Balai'),
( 12,'Kota Binjai'),
( 12,'Kota Tebing Tinggi'),
( 12,'Kota Padangsidimpuan'),
( 12,'Kota Gunungsitoli'),
( 13,'Pesisir Selatan'),
( 13,'Solok'),
( 13,'Sijunjung'),
( 13,'Tanah Datar'),
( 13,'Padang Pariaman'),
( 13,'Agam'),
( 13,'Lima Puluh Kota'),
( 13,'Pasaman'),
( 13,'Kepulauan Mentawai'),
( 13,'Dharmasraya'),
( 13,'Solok Selatan'),
( 13,'Pasaman Barat'),
( 13,'Kota Padang'),
( 13,'Kota Solok'),
( 13,'Kota Sawahlunto'),
( 13,'Kota Padang Panjang'),
( 13,'Kota Bukittinggi'),
( 13,'Kota Payakumbuh'),
( 13,'Kota Pariaman'),
( 14,'Kampar'),
( 14,'Indragiri Hulu'),
( 14,'Bengkalis'),
( 14,'Indragiri Hilir'),
( 14,'Pelalawan'),
( 14,'Rokan Hulu'),
( 14,'Rokan Hilir'),
( 14,'Siak'),
( 14,'Kuantan Singingi'),
( 14,'Kepulauan Meranti'),
( 14,'Kota Pekanbaru'),
( 14,'Kota Dumai'),
( 15,'Kerinci'),
( 15,'Merangin'),
( 15,'Sarolangun'),
( 15,'Batanghari'),
( 15,'Muaro Jambi'),
( 15,'Tanjung Jabung Barat'),
( 15,'Tanjung Jabung Timur'),
( 15,'Bungo'),
( 15,'Tebo'),
( 15,'Kota Jambi'),
( 15,'Kota Sungai Penuh'),
( 16,'Ogan Komering Ulu'),
( 16,'Ogan Komering Ilir'),
( 16,'Muara Enim'),
( 16,'Lahat'),
( 16,'Musi Rawas'),
( 16,'Musi Banyuasin'),
( 16,'Banyu Asin'),
( 16,'Ogan Komering Ulu Selatan'),
( 16,'Ogan Komering Ulu Timur'),
( 16,'Empat Lawang'),
( 16,'Kota Palembang'),
( 16,'Kota Prabumulih'),
( 16,'Kota Pagar Alam'),
( 16,'Kota Lubuklinggau'),
( 17,'Bengkulu Selatan'),
( 17,'Rejang Lebong'),
( 17,'Bengkulu Utara'),
( 17,'Kaur'),
( 17,'Seluma'),
( 17,'Muko Muko'),
( 17,'Lebong'),
( 17,'Kepahiang'),
( 17,'Kota Bengkulu'),
( 18,'Lampung Selatan'),
( 18,'Lampung Tengah'),
( 18,'Lampung Utara'),
( 18,'Lampung Barat'),
( 18,'Tulang Bawang'),
( 18,'Tanggamus'),
( 18,'Lampung Timur'),
( 18,'Way Kanan'),
( 18,'Pesawaran'),
( 18,'Pringsewu'),
( 18,'Mesuji'),
( 18,'Tulang Bawang Barat'),
( 18,'Pesisir Barat'),
( 18,'Kota Bandar Lampung'),
( 18,'Kota Metro'),
( 19,'Bangka'),
( 19,'Belitung'),
( 19,'Bangka Selatan'),
( 19,'Bangka Tengah'),
( 19,'Belitung Timur'),
( 19,'Bangka Barat'),
( 19,'Kota Pangkal Pinang'),
( 21,'Karimun'),
( 21,'Bintan'),
( 21,'Natuna'),
( 21,'Lingga'),
( 21,'Kepulauan Anambas'),
( 21,'Kota Batam'),
( 21,'Kota Tanjung Pinang'),
( 31,'Kepulauan Sangihe'),
( 31,'Kepulauan Talaud'),
( 31,'Minahasa'),
( 31,'Minahasa Selatan'),
( 31,'Minahasa Utara'),
( 31,'Bolaang Mongondow'),
( 31,'Minahasa Tenggara'),
( 31,'Kepulauan Siau Tagulandang Biaro (Sitaro)'),
( 31,'Bolaang Mongondow Utara'),
( 31,'Bolaang Mongondow Selatan'),
( 31,'Bolaang Mongondow Timur'),
( 31,'Kota Manado'),
( 31,'Kota Bitung'),
( 31,'Kota Tomohon'),
( 31,'Kota Kotamobagu'),
( 32,'Tanah Datar'),
( 32,'Pasaman Barat'),
( 32,'Padang Pariaman'),
( 32,'Sijunjung'),
( 32,'Pesisir Selatan'),
( 32,'Solok Selatan'),
( 32,'Lima Puluh Kota'),
( 32,'Agam'),
( 32,'Kepulauan Mentawai'),
( 32,'Solok'),
( 32,'Dharmasraya'),
( 32,'Kota Padang'),
( 32,'Kota Bukittinggi'),
( 32,'Kota Solok'),
( 32,'Kota Sawahlunto'),
( 32,'Kota Payakumbuh'),
( 32,'Kota Pariaman'),
( 33,'Tapanuli Selatan'),
( 33,'Tapanuli Tengah'),
( 33,'Tapanuli Utara'),
( 33,'Mandailing Natal'),
( 33,'Humbang Hasundutan'),
( 33,'Padang Lawas Utara'),
( 33,'Padang Lawas'),
( 33,'Labuhanbatu'),
( 33,'Labuhanbatu Selatan'),
( 33,'Labuhanbatu Utara'),
( 33,'Samosir'),
( 33,'Karo'),
( 33,'Pakpak Bharat'),
( 33,'Deli Serdang'),
( 33,'Langkat'),
( 33,'Serdang Bedagai'),
( 33,'Asahan'),
( 33,'Simalungun'),
( 33,'Batu Bara'),
( 33,'Kota Medan'),
( 33,'Kota Binjai'),
( 33,'Kota Sibolga'),
( 33,'Kota Pematang Siantar'),
( 33,'Kota Tanjung Balai'),
( 33,'Kota Tebing Tinggi'),
( 33,'Kota Padangsidimpuan'),
( 33,'Kota Gunung Sitoli'),
( 34,'Dairi'),
( 34,'Deli Serdang'),
( 34,'Langkat'),
( 34,'Labuhanbatu'),
( 34,'Padang Lawas'),
( 34,'Nias'),
( 34,'Toba'),
( 34,'Mandailing Natal'),
( 34,'Karo'),
( 34,'Kota Medan'),
( 34,'Kota Pematang Siantar'),
( 34,'Kota Gunung Sitoli'),
( 34,'Kota Tebing Tinggi')
